# Generated by Django 4.0.4 on 2023-08-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='users',
            new_name='user',
        ),
    ]
